// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('draw_simple_route', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('draw_simple_route', async function() {
    await driver.get("http://192.168.49.2:30000/")
    await driver.manage().window().setRect({ width: 2560, height: 1411 })
    await driver.findElement(By.css("scouter-web")).click()
    {
      const element = await driver.findElement(By.css("scouter-web"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css("scouter-web"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css("scouter-web"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("scouter-web")).click()
    await driver.findElement(By.css("scouter-web")).click()
    await driver.findElement(By.css("scouter-web")).click()
  })
})
