apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-service
  namespace: movona
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: gatekeeper
