apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-deployment
  namespace: movona
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gatekeeper-app
  template:
    metadata:
      labels:
        name: gatekeeper-app
        app: gatekeeper
    spec:
      containers:
        - name: gatekeeper-app
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: gatekeeper-conf-fs
      volumes:
        - name: gatekeeper-conf-fs
          hostPath:
            path: /movona/gatekeeper/conf/default.conf
            type: File
        - name: gatekeeper-doc-fs
          hostPath:
            path: /movona/gatekeeper/app
            type: Directory
