apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-deployment
  namespace: movona
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gatekeeper-app
  template:
    metadata:
      labels:
        name: gatekeeper-app
        app: gatekeeper
    spec:
      containers:
        - name: gatekeeper-app
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: gatekeeper-conf-fs
            - mountPath: /etc/nginx/jwt_auth.js
              name: gatekeeper-js-module
      volumes:
        - name: gatekeeper-conf-fs
          hostPath:
            path: /movona/gatekeeper/conf/nginx.conf
            type: File
        - name: gatekeeper-js-module
          hostPath:
            path: /movona/gatekeeper/conf/jwt_auth.js
            type: File
        - name: gatekeeper-doc-fs
          hostPath:
            path: /movona/gatekeeper/app
            type: Directory
#  docker run --rm -v $PWD/conf/nginx.conf:/etc/nginx/nginx.conf -v $PWD/conf/jwt_auth.js:/etc/nginx/jwt_auth.js movona/gatekeeper:1.0.0.20221203
