apiVersion: v1
kind: Service
metadata:
  name: planner-web-service
  namespace: movona
spec:
  type: ClusterIP
  ports:
  - port: 30100
    targetPort: 4200
    protocol: TCP
  selector:
    app: planner-web
