apiVersion: v1
kind: Service
metadata:
  name: scouter-web-service
  namespace: movona
spec:
  type: ClusterIP
  ports:
  - port: 30080
    targetPort: 8080
    protocol: TCP
  selector:
    app: scouter-web
